[tool.black]
line-length = 79
skip-string-normalization = true
docstring-style = "google"

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
sections = "STDLIB,FIRSTPARTY,THIRDPARTY,LOCALFOLDER"
known_local_folder = ["app"]