# Generated by Django 4.2 on 2023-04-23 15:12

import apps.base.validators.country

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    def create_countries():
        # Adding new money users profiles
        query = """
        INSERT INTO public.countries (id, name, active, created_at, updated_at) VALUES (1, 'colombia', true, now(), now());
        ALTER SEQUENCE countries_id_seq RESTART WITH 2;
        """
        return query

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=64,
                        validators=[
                            apps.base.validators.country.validate_name
                        ],
                    ),
                ),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.RunSQL(create_countries()),
    ]
