# Generated by Django 4.2 on 2023-04-27 14:24

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                ('email', models.EmailField(max_length=128, unique=True)),
                (
                    'first_name',
                    models.CharField(
                        max_length=128,
                        validators=[apps.users.validators.validate_first_name],
                    ),
                ),
                (
                    'last_name',
                    models.CharField(
                        max_length=128,
                        validators=[apps.users.validators.validate_last_name],
                    ),
                ),
                (
                    'phone',
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        validators=[apps.users.validators.validate_phone],
                    ),
                ),
                (
                    'nid',
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        validators=[apps.users.validators.validate_nid],
                    ),
                ),
                (
                    'birth',
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[apps.users.validators.validate_birth],
                    ),
                ),
                ('password', models.CharField(max_length=128)),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('active', 'active'),
                            ('inactive', 'inactive'),
                            ('pending', 'pending'),
                        ],
                        default='pending',
                        max_length=16,
                    ),
                ),
                (
                    'profile',
                    models.CharField(
                        choices=[
                            ('administrator', 'administrator'),
                            ('coordinator', 'coordinator'),
                            ('student', 'student'),
                            ('support', 'support'),
                            ('teacher', 'teacher'),
                            ('user', 'user'),
                        ],
                        default='user',
                        max_length=16,
                    ),
                ),
                (
                    'country',
                    models.CharField(
                        choices=[
                            ('colombia', 'colombia'),
                            ('ecuador', 'ecuador'),
                            ('spain', 'spain'),
                            ('mexico', 'mexico'),
                            ('peru', 'peru'),
                        ],
                        max_length=32,
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
