# Generated by Django 4.2 on 2023-04-23 15:12

import apps.users.validators.user
import apps.users.validators.user_profile

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='users',
                to='base.country',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(
                null=True,
                validators=[apps.users.validators.user.validate_birth],
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='nid',
            field=models.CharField(
                max_length=16,
                null=True,
                validators=[apps.users.validators.user.validate_nid],
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(
                max_length=16,
                null=True,
                validators=[apps.users.validators.user.validate_phone],
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(
                max_length=64,
                validators=[apps.users.validators.user_profile.validate_name],
            ),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='name',
            field=models.CharField(
                max_length=64,
                validators=[apps.users.validators.user_profile.validate_name],
            ),
        ),
    ]
